common: &common
  adapter: postgresql
  username: sample_app
  password: sample

development:
  <<: *common
  database: sampleapp_development

test:
  <<: *common
  database: sampleapp_test

production:
  <<: *common
  database: sampleapp_production